testinfo:
    - id: test_settings_002
      title: 设置-意见反馈相关
      info: 设置-意见反馈相关测试
testcase:
    - element_info: $tab_personal
      find_type: $id
      operate_type: click
      info: 点击'我'按钮

    - element_info: $setting_btn
      find_type: $id
      operate_type: click
      info: 点击'设置'按钮

    - element_info: $block_list
      find_type: $text
      operate_type: swipe_up
      info: 向上滑动

    - element_info: $fb_btn
      find_type: $id
      operate_type: click
      info: 点击'意见反馈'

    - element_info: $fb_back
      find_type: $id
      operate_type: click
      info: 返回设置页

    - element_info: $btn_watermark
      find_type: $text
      operate_type: swipe_down
      info: 向下滑动

check:
    - element_info: $block_list
      find_type: $text
      check: default_check
      info: 验证返回设置页面