testinfo:
    - id: test_settings_comm
      title: 设置-基本设置相关
      info: 设置-基本设置相关测试
testcase:
    - element_info: $el_personal
      find_type: $id
      operate_type: click
      info: 点击'我'按钮

    - element_info: $setting_btn
      find_type: $id
      operate_type: click
      info: 点击'设置'按钮

    - element_info: $net_disable
      find_type: $id
      operate_type: click
      info: 关闭'只在Wi-Fi上传/下载'

    - element_info: $rec_notice
      find_type: $text
      operate_type: click
      info: 点击'接收通知推送'

    - element_info: $rec_checkbox
      find_type: $id
      operate_type: click
      info: 任意关闭一个通知推送设置

    - element_info: $rec_back
      find_type: $id
      operate_type: click
      info: 返回设置页

    - element_info: $rec_lang
      find_type: $text
      operate_type: click
      info: 点击'已选择语言'

    - element_info: $lang_back
      find_type: $id
      operate_type: click
      info: 返回设置页

check:
    - element_info: $privac_set
      find_type: $text
      check: default_check
      info: 设置-基本设置相关测试验证