testinfo:
    - id: test_settings_feedback
      title: 设置-意见反馈相关
      info: 设置-意见反馈相关测试
testcase:
    - element_info: $el_personal
      find_type: $id
      operate_type: click
      info: 点击'我'按钮

    - element_info: $setting_btn
      find_type: $id
      operate_type: click
      info: 点击'设置'按钮

    - element_info:
      find_type:
      operate_type: swipeToUp
      info: 向上滑动

    - element_info:
      find_type:
      operate_type: swipeToUp
      info: 向上滑动

    - element_info: $fb_btn
      find_type: $id
      operate_type: click
      info: 点击'意见反馈'

    - element_info: $fb_edit
      find_type: $id
      operate_type: set_value
      msg: 退款
      info: 点击问题编辑输入框

    - element_info: $fb_send
      find_type: $id
      operate_type: ckick
      info: 发送问题

    - element_info: $fb_read
      find_type: $text
      operate_type: ckick
      info: 阅读全部

    - element_info: $fb_back
      find_type: $id
      operate_type: ckick
      info: 返回反馈页面

    - element_info: $fb_kefu
      find_type: $id
      operate_type: ckick
      info: 人工客服

    - element_info: $kefu_cancel
      find_type: $text
      operate_type: ckick
      info: 不用了

    - element_info: $fb_kefu
      find_type: $id
      operate_type: ckick
      info: 人工客服

    - element_info: $kefu_cancel
      find_type: $text
      operate_type: ckick
      info: 好的
















    - element_info: $rec_back
      find_type: $id
      operate_type: click
      info: 返回设置页

    - element_info: $block_list
      find_type: $text
      operate_type: click
      info: 点击'黑名单'

    - element_info: $block_list
      find_type: $text
      operate_type: click
      info: 点击'黑名单'

    - element_info: $block_remove
      find_type: $text
      operate_type: ignore
      info: 移除一个用户

    - element_info: $rec_back
      find_type: $id
      operate_type: click
      info: 返回设置页

    - element_info: $privacy_disable
      find_type: $id
      operate_type: click
      info: 关闭隐私账号设置

    - element_info: $watermark_enable
      find_type: $id
      operate_type: click
      info: 水印显示昵称
check:
    - element_info: $watermark_enable
      find_type: $id
      check: default_check
      info: 设置-意见反馈相关测试验证